const RECIPE = {
  CREATE: "RECIPE.CREATE",
  UPDATE: "RECIPE.UPDATE",
  DELETE: "RECIPE.DELETE",
};

const BATCH = {
  COOK: "BATCH.COOK",
  UNLIMITED_COOK: "BATCH.UNLIMITED_COOK",
  BASIC_UPDATE: "BATCH.BASIC_UPDATE",
  DELETE: "BATCH.DELETE",
};

export const PERMISSIONS = { RECIPE, BATCH };
