const RECIPE = {
  CREATE: "RECIPE.CREATE",
  UPDATE: "RECIPE.UPDATE",
  DELETE: "RECIPE.DELETE",
  SCRAP: "RECIPE.SCRAP",
};

const BATCH = {
  READ: "BATCH.READ",
  COOK: "BATCH.COOK",
  UNLIMITED_COOK: "BATCH.UNLIMITED_COOK",
  BASIC_UPDATE: "BATCH.BASIC_UPDATE",
  DELETE: "BATCH.DELETE",
};

const BASKET = { READ: "BASKET.READ" };

export const PERMISSIONS = { RECIPE, BATCH, BASKET, ADMIN: "admin" };
